server.port=8084
spring.application.name=booking-service

spring.datasource.url=jdbc:postgresql://localhost:5432/eventbooking
spring.datasource.username=eventuser
spring.datasource.password=eventpass
spring.jpa.hibernate.ddl-auto=update

# Feign clients
user.service.url=localhost:8081
event.service.url=localhost:8082
venue.service.url=localhost:8083
notification.service.url=localhost:8085
